language: node_js
node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${{ secrets.GITHUB_TOKEN }} 
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: workflowcheck
